name: retail_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  mobile_scanner: ^5.1.1
  device_info_plus: ^9.0.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2
  sqflite: ^2.3.0
  sqflite_common_ffi_web: 1.1.1
  path: 1.9.1
  url_launcher: ^6.3.2
  file_picker: ^8.0.0
  connectivity_plus: ^6.0.3
  crypto: ^3.0.3
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/icon/savidor.png


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/savidor.png"
  
  web:
    generate: true
    image_path: "assets/icon/savidor.png"
    background_color: "#4F6EF7"
    theme_color: "#4F6EF7"
    
  windows:
    generate: true
    image_path: "assets/icon/savidor.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icon/savidor.png"
